# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('img', models.CharField(max_length=100)),
                ('store_num', models.IntegerField(default=20)),
            ],
            options={
                'db_table': '网易考拉——商品',
            },
        ),
    ]
